main: net.tfminecraft.advancedcrafting.AdvancedCrafting
api-version: '1.21.10'
name: AdvancedCrafting
version: ${project.version}
author: Drefvelin

depend: [TLibs, MMOCore, MMOItems, MythicLib]

commands:
  ac:
    useage: /<command>
    description: AdvancedCrafting Command
  alloy:
    useage: /<command>
    description: Alloy Command

permissions:
  advancedcrafting.admin:
    description: AdvancedCrafting admin commands
    default: op
